export enum PostsConstants {
  SET_POSTS = 'posts/SET_POSTS',
  GET_POST_DETAILS = 'posts/GET_POST_DETAILS',
  SET_CURRENT_POST = 'posts/SET_CURRENT_POST',

  EDIT_POST = 'posts/EDIT_POST',
  ADD_POST = 'posts/ADD_POST',
  DEL_POST = 'posts/DEL_POST',

  SET_RESPONSE_ERROR = 'posts/SET_RESPONSE_ERROR',
  SET_FORM_ERROR = 'posts/SET_FORM_ERROR',
  SET_SUCCESS_MESSAGE = 'posts/SET_SUCCESS_MESSAGE',

  SET_IS_POSTS_FETCHING = 'posts/SET_IS_DATA_FETCHING',

  SET_IS_DELETING_POST = 'posts/SET_IS_DELETING_POST',
  SET_IS_SAVING_POST = 'posts/SET_IS_SAVING_POST',
}
