export enum AuthorsConstants {
  SET_AUTHORS = 'authors/SET_AUTHORS',
  GET_AUTHORS = 'authors/GET_AUTHORS',

  GET_AUTHOR_DETAILS = 'authors/GET_AUTHOR_DETAILS',
  SET_CURRENT_AUTHOR = 'authors/SET_CURRENT_AUTHOR',

  EDIT_AUTHOR = 'authors/EDIT_AUTHOR',
  ADD_AUTHOR = 'authors/ADD_AUTHOR',
  DEL_AUTHOR = 'authors/DEL_AUTHOR',
  MULTIPLE_DEL_AUTHORS = 'authors/MULTIPLE_DEL_AUTHORS',

  SET_RESPONSE_ERROR = 'authors/SET_RESPONSE_ERROR',
  SET_FORM_ERROR = 'authors/SET_FORM_ERROR',
  SET_SUCCESS_MESSAGE = 'authors/SET_SUCCESS_MESSAGE',

  SET_IS_DELETING_AUTHOR = 'authors/SET_IS_DELETING_AUTHOR',
  SET_IS_MULTI_DELETING_AUTHOR = 'authors/SET_IS_MULTI_DELETING_AUTHOR',
  SET_IS_SAVING_AUTHOR = 'authors/SET_IS_SAVING_AUTHOR',
}
