export enum AuthConstants {
  SET_IS_AUTH = 'auth/SET_IS_AUTH',
  GET_AUTH_DATA = 'auth/GET_AUTH_DATA',
  LOGOUT_FROM_ACCOUNT = 'auth/LOGOUT_FROM_ACCOUNT',

  IS_FETHCHING_AUTH_DATA = 'auth/IS_FETHCHING_AUTH_DATA',

  SET_PROFILE_INFO = 'auth/SET_PROFILE_INFO',
  GET_PROFILE_INFO = 'auth/GET_PROFILE_INFO',

  SET_RESPONSE_ERROR = 'auth/SET_RESPONSE_ERROR',
  SET_FORM_ERROR = 'auth/SET_FORM_ERROR',

  SET_AUTH_ERROR_MESSAGE = 'auth/SET_AUTH_ERROR_MESSAGE',
}
